#!/usr/bin/env node

global.fetch = require("cross-fetch");

const wisCheckStatus = require("./modules/wis/wis").wisCheckStatus;
const oneguardCheckStatus = require("./modules/oneguard/oneguard").oneguardCheckStatus;

const options = require("./utils/get-options.js").getOptions();

/*
    prcoCheckStatus
*/
const prcoCheckStatus = async () =>
  options.server === "wis" ? await wisCheckStatus(options) : await oneguardCheckStatus(options);

prcoCheckStatus();
